pre-push:
    - run:
        command: set -o pipefail && swift test 2>&1 | xcpretty --color
        critical: false
pre-commit:
    - swift-run:
        command: swiftformat .
        configuration: release
        package-path: BuildTools
    - swift-run:
        command: swiftlint lint --strict .
        configuration: release
        package-path: BuildTools
        verbose: false
        critical: true
    - run:
        command: swift test --generate-linuxmain
        verbose: false
    - swift-run:
        command: periphery scan
        configuration: release
        package-path: BuildTools
    - git add -A
