pre-push:
    - set -o pipefail && swift test 2>&1 | xcpretty --color
pre-commit:
    - run: 
        command: set -o pipefail && swift test 2>&1 | xcpretty --color   
        critical: false
        verbose: false
