pre-push:
    - run:
        command: set -o pipefail && swift test 2>&1 | xcpretty --color
        critical: false
pre-commit:
    - run:
        command: swift run -c release --package-path BuildTools swiftformat .
        verbose: false
    - run:
        command: swift run -c release --package-path BuildTools swiftlint lint --strict .
        verbose: false
        critical: true
    - run:
        command: swift test --generate-linuxmain
        verbose: false  
    - git add -A
