disabled_rules:
  - trailing_comma
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build 
  - BuildTools/.build
  - .idea
  - XCTestManifests.swift
line_length:
  warning: 200
  ignores_comments: true
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
identifier_name:
  excluded:
    - fm
