#if !canImport(ObjectiveC)
import XCTest

extension ShuskyCoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShuskyCoreTests = [
        ("testReadShuskyYml", testReadShuskyYml),
        ("testShuskyFileName", testShuskyFileName),
        ("testShuskyFilePath", testShuskyFilePath),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ShuskyCoreTests.__allTests__ShuskyCoreTests),
    ]
}
#endif
