#if !canImport(ObjectiveC)
import XCTest

extension HookHandlerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HookHandlerTests = [
        ("testAddHook", testAddHook),
        ("testAddHookWithPackagePath", testAddHookWithPackagePath),
        ("testAppendHook", testAppendHook),
        ("testAppendHookWithPackagePath", testAppendHookWithPackagePath),
        ("testCreateHookFileIfNotExists", testCreateHookFileIfNotExists),
        ("testExecutionPermissions", testExecutionPermissions),
    ]
}

extension ShuskyFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShuskyFileTests = [
        ("testCreateDefaultShuskyYamlFile", testCreateDefaultShuskyYamlFile),
        ("testCreateFile", testCreateFile),
        ("testDontCreateDefaultShuskyYamlFileIfNotEmpty", testDontCreateDefaultShuskyYamlFileIfNotEmpty),
        ("testReadShuskyYml", testReadShuskyYml),
        ("testShuskyFileName", testShuskyFileName),
        ("testShuskyFilePath", testShuskyFilePath),
    ]
}

extension ShuskyModelsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShuskyModelsTests = [
        ("testEmptyYaml", testEmptyYaml),
        ("testHooksParser", testHooksParser),
        ("testHookTypeEnum", testHookTypeEnum),
        ("testInvalidCommand", testInvalidCommand),
        ("testInvalidTypeVerboseInHook", testInvalidTypeVerboseInHook),
        ("testNoHookFound", testNoHookFound),
        ("testParseComplexConfig", testParseComplexConfig),
        ("testParseSimpleConfig", testParseSimpleConfig),
        ("testRunWithCommandDefined", testRunWithCommandDefined),
        ("testRunWithCommandPathCriticalDefined", testRunWithCommandPathCriticalDefined),
        ("testRunWithCommandPathCriticalVerboseDefined", testRunWithCommandPathCriticalVerboseDefined),
        ("testRunWithCommandPathDefined", testRunWithCommandPathDefined),
        ("testRunWithInvalidTypeCommand", testRunWithInvalidTypeCommand),
        ("testRunWithInvalidTypeCritical", testRunWithInvalidTypeCritical),
        ("testRunWithInvalidTypePath", testRunWithInvalidTypePath),
        ("testRunWithInvalidTypeVerbose", testRunWithInvalidTypeVerbose),
        ("testRunWithNoCommandDefined", testRunWithNoCommandDefined),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HookHandlerTests.__allTests__HookHandlerTests),
        testCase(ShuskyFileTests.__allTests__ShuskyFileTests),
        testCase(ShuskyModelsTests.__allTests__ShuskyModelsTests),
    ]
}
#endif
