name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
      name: Build and test on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [macos-latest, ubuntu-20.04]
      steps:
        - uses: actions/checkout@v2
        - name: Run swiftformat lint
          if: ${{ matrix.os == 'macos-latest' }}
          run: swift run --package-path BuildTools swiftformat --lint .
        - name: Run swiftlint
          if: ${{ matrix.os == 'macos-latest' }}
          run: swift run --package-path BuildTools swiftlint lint --strict .
        - name: Build
          run: swift build -v
        - name: Run tests
          run: swift test -v
