name: Ubuntu 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
      name: Build and test in Ubuntu 20.02
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: 2.6 # Not needed with a .ruby-version file
            bundler-cache: true # 
        - uses: actions/checkout@v2
        - name: Build
          run: swift build -v
        - name: Run tests
          run: swift test -v
