#if !canImport(ObjectiveC)
    import XCTest

    extension ShuskyTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ShuskyTests = [
            ("testExample", testExample),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(ShuskyTests.__allTests__ShuskyTests),
        ]
    }
#endif
